export type ExplainerSource = 'gtm' | 'ads' | 'report' | 'cross' | 'meta' | 'tiktok' | 'linkedin' | 'pinterest' | 'twitter' | 'snapchat';

export interface CheckExplainer {
  id: string;
  name: string;
  source: ExplainerSource;
  severity: 'critical' | 'warning' | 'info';
  summary: string;
  why: string;
  howToFix: string;
  example?: string;
  relatedChecks?: string[];
}

export const explainerSources: { key: ExplainerSource; label: string }[] = [
  { key: 'gtm', label: 'Google Tag Manager' },
  { key: 'ads', label: 'Google Ads' },
  { key: 'report', label: 'Performance Reports' },
  { key: 'cross', label: 'Cross-Source' },
  { key: 'meta', label: 'Meta Pixel' },
  { key: 'tiktok', label: 'TikTok Pixel' },
  { key: 'linkedin', label: 'LinkedIn Insight Tag' },
  { key: 'pinterest', label: 'Pinterest Tag' },
  { key: 'twitter', label: 'Twitter/X Pixel' },
  { key: 'snapchat', label: 'Snapchat Pixel' },
];

export const explainers: CheckExplainer[] = [
  {
    id: 'missing-conversion-linker',
    name: 'Missing Google Ads Conversion Linker',
    source: 'gtm',
    severity: 'critical',
    summary: 'The GTM container does not have a Google Ads Conversion Linker firing on the site.',
    why: 'The Conversion Linker writes and refreshes the first-party click identifiers Google Ads uses to connect ad clicks to later conversions. Without it, cross-domain funnels, cookie restrictions, and delayed purchases can lose attribution. That usually shows up as underreported conversions and ROAS, which can push budget away from campaigns that are actually working.',
    howToFix: 'In Google Tag Manager, create a Google Ads Conversion Linker tag and set it to fire on All Pages. If checkout or lead capture happens on another domain, configure linker domains for every domain in the funnel. Preview the container, confirm the tag fires before conversion tags, then publish.',
    example: 'Tag type: Google Ads Conversion Linker\nTrigger: All Pages\nCross-domain domains: example.com, checkout.example-payments.com',
    relatedChecks: ['conversion-linker-sequencing', 'conversion-label-matching'],
  },
  {
    id: 'consent-violations',
    name: 'Google Ads Tags May Fire Without Consent',
    source: 'gtm',
    severity: 'warning',
    summary: 'Google Ads tags may be able to fire before the required consent state is granted.',
    why: 'If ad tags fire before consent in regions that require it, the setup can create compliance risk and pollute measurement with hits that should have been blocked or modeled differently. Consent mistakes also make debugging hard because the same tag can behave differently by geography, consent banner timing, and browser state. Advertisers end up with unstable conversion volume and a setup that is difficult to defend.',
    howToFix: 'Use GTM consent settings or Consent Mode so Google Ads conversion and remarketing tags require the right ad_storage and ad_user_data states. Make the consent banner set default denied before tags load, then update consent after the user choice. Test denied, granted, and changed-consent paths in GTM Preview before publishing.',
    example: 'Required consent checks: ad_storage, ad_user_data, ad_personalization\nDefault state before banner choice: denied',
    relatedChecks: ['missing-conversion-linker', 'conversion-label-matching'],
  },
  {
    id: 'duplicate-conversions',
    name: 'Duplicate Conversion Tracking',
    source: 'cross',
    severity: 'critical',
    summary: 'Duplicate conversion tags or conversion actions can double-count the same business event.',
    why: 'This ID is emitted by both GTM duplicate tag checks and Google Ads duplicate conversion action checks. Either failure can inflate conversion volume, conversion value, and Smart Bidding signals. The advertiser sees better-looking CPA or ROAS than reality, while bidding algorithms learn from repeated copies of the same event.',
    howToFix: 'In GTM, compare Google Ads conversion tags by conversion ID, conversion label, and trigger; remove duplicates or narrow triggers so one business event fires one tag. In Google Ads, consolidate duplicate conversion actions, keep the canonical action Primary, and mark test or backup actions Secondary or remove them. Re-run the audit after one full conversion cycle to confirm counts return to expected levels.',
    example: 'Duplicate pattern: two Ads conversion tags with the same AW-123456789 / abcDEF_label firing on purchase_success',
    relatedChecks: ['volume-weighted-duplicates', 'conversion-label-matching', 'tag-count-mismatch'],
  },
  {
    id: 'ecommerce-datalayer-structure',
    name: 'E-commerce Data Layer Structure',
    source: 'gtm',
    severity: 'critical',
    summary: 'The dataLayer does not expose purchase and item data in a reliable e-commerce shape.',
    why: 'Google Ads, GA4, Meta, TikTok, and server-side pipelines all depend on stable event names and value fields. If purchase data is missing or nested unpredictably, conversion tags fall back to fixed values, zero values, or no item data. That breaks ROAS reporting, product-level diagnostics, and remarketing audiences.',
    howToFix: 'Standardize the purchase event payload before GTM tags fire. Include transaction_id, value, currency, and an items array with item_id, item_name, price, and quantity. Validate the payload in GTM Preview and your browser console on real purchase and refund paths.',
    example: "dataLayer.push({ event: 'purchase', ecommerce: { transaction_id: 'T123', value: 129.99, currency: 'USD', items: [{ item_id: 'SKU-1', price: 129.99, quantity: 1 }] } });",
    relatedChecks: ['missing-datalayer-variables', 'zero-value-purchases', 'value-mismatch'],
  },
  {
    id: 'missing-datalayer-variables',
    name: 'Missing Data Layer Variables',
    source: 'gtm',
    severity: 'warning',
    summary: 'GTM tags reference dataLayer values that are missing or not configured as variables.',
    why: 'A tag can exist and fire while still sending empty conversion value, currency, transaction ID, or user data fields. That creates silent tracking degradation: conversions count, but value-based bidding and deduplication do not work correctly. Engineers usually discover this only after report values look impossible or duplicate rates climb.',
    howToFix: 'Create GTM Data Layer Variables for every field used by conversion tags, including ecommerce.value, ecommerce.currency, ecommerce.transaction_id, and user-data fields where applicable. Confirm each variable resolves on the exact trigger event, not only after the page has fully loaded. Add fallback handling only when a missing value is expected and harmless.',
    example: 'Variable: DLV - ecommerce.value\nData Layer Variable Name: ecommerce.value\nUsed by: Google Ads purchase conversion value',
    relatedChecks: ['ecommerce-datalayer-structure', 'dynamic-value-passing'],
  },
  {
    id: 'zero-value-purchases',
    name: 'Purchase Conversions with Zero Value',
    source: 'ads',
    severity: 'critical',
    summary: 'Purchase or sale conversion actions are configured with no revenue value.',
    why: 'Zero-value purchases make revenue reporting and ROAS bidding unusable. Google Ads can still count conversions, but it cannot distinguish a $10 order from a $1,000 order. That pushes optimization toward volume instead of profit and can make high-revenue campaigns look no better than low-revenue ones.',
    howToFix: 'For e-commerce, set the Google Ads conversion action to use different values for each conversion and pass the transaction value from GTM or your site tag. For lead generation, assign realistic lead values if you use value-based bidding, or keep these actions out of ROAS workflows. Verify that recent conversions show non-zero conversion value in Google Ads reports.',
    example: 'Google Ads conversion value setting: Use different values for each conversion\nGTM value parameter: {{DLV - ecommerce.value}}',
    relatedChecks: ['roas-feasibility', 'roas-sanity', 'value-mismatch'],
  },
  {
    id: 'missing-primary-conversion',
    name: 'Missing Primary Conversion',
    source: 'ads',
    severity: 'warning',
    summary: 'Google Ads has no enabled purchase or sale conversion action suitable as the primary bidding goal.',
    why: 'Smart Bidding optimizes toward Primary conversions. If the actual business outcome is missing, disabled, or treated as Secondary, campaigns may optimize toward weaker actions such as page views, signups, or add-to-cart events. The account can look active while bidding is pointed at the wrong goal.',
    howToFix: 'In Google Ads, choose the main business outcome and mark it Primary in the conversion goal settings. Keep diagnostic, micro, and imported backup actions as Secondary unless they should directly influence bidding. Confirm campaign goals include the selected primary action and exclude unrelated account-default goals.',
    example: 'Primary: Purchase\nSecondary: Add to cart, Begin checkout, Newsletter signup',
    relatedChecks: ['micro-conversion-pollution', 'smart-bidding-volume'],
  },
  {
    id: 'smart-bidding-volume',
    name: 'Smart Bidding Readiness',
    source: 'ads',
    severity: 'warning',
    summary: 'The account may not have enough enabled primary conversion volume for stable Smart Bidding.',
    why: 'Smart Bidding needs enough recent, consistent conversion signal to learn. Very low volume or no primary conversions forces the model to optimize from sparse data, delayed feedback, or secondary goals. That can create volatile CPA, slow learning periods, and budget movement based on noise.',
    howToFix: 'Check the last 30 days of conversion volume for each primary action used by campaigns. Use Maximize Conversions or tCPA only when the primary action has enough regular volume, and avoid splitting the same event across many duplicate actions. If volume is low, consolidate goals or start with a broader but still meaningful conversion until the macro event has enough data.',
    example: 'Healthy target: 15-30+ primary conversions per month per bidding portfolio before aggressive tCPA or tROAS constraints',
    relatedChecks: ['missing-primary-conversion', 'micro-conversion-pollution'],
  },
  {
    id: 'short-attribution-windows',
    name: 'Attribution Window Too Short',
    source: 'ads',
    severity: 'warning',
    summary: 'Conversion click windows are shorter than the likely sales cycle.',
    why: 'A window that is too short drops legitimate conversions that happen days or weeks after the click. This underreports campaigns with longer consideration cycles and makes upper-funnel or remarketing traffic look weaker than it is. Bidding then learns from incomplete feedback and can over-favor immediate converters.',
    howToFix: 'Compare the click-through conversion window to the actual time from ad click to purchase or lead. In Google Ads conversion settings, extend the window for conversions with medium or long sales cycles, commonly to 14, 30, or 60 days depending on the business. Keep short windows only when purchases are genuinely immediate.',
    example: 'Problem: B2B demo request uses a 3-day click window while the median click-to-lead delay is 12 days',
    relatedChecks: ['model-attribution-drift', 'long-attribution-windows'],
  },
  {
    id: 'vtc-click-ratio',
    name: 'Greedy Impression Index',
    source: 'report',
    severity: 'warning',
    summary: 'View-through conversions are more than 3x click-driven conversions for one or more actions.',
    why: 'A high view-through to click ratio can make display, video, or remarketing campaigns appear to drive more incremental performance than they really do. View-through conversions are impression-based, so long windows can claim credit for users who would have converted anyway. The advertiser may overfund prospecting or remarketing that is mostly harvesting post-impression credit.',
    howToFix: 'Review the view-through conversion window for flagged actions in Google Ads. Shorten the VTC window, separate VTC-heavy actions from bidding decisions, and compare performance using click conversions or experiments. For high-stakes budget decisions, evaluate incrementality instead of treating VTC and click conversions as equivalent.',
    example: 'Conversions: 40 total\nView-through conversions: 32\nClick conversions: 8\nVTC/click ratio: 4.0x',
    relatedChecks: ['model-attribution-drift', 'roas-sanity'],
  },
  {
    id: 'roas-sanity',
    name: 'ROAS Sanity',
    source: 'report',
    severity: 'warning',
    summary: 'Reported ROAS is suspiciously high or low for conversion actions with meaningful volume.',
    why: 'Extreme ROAS values usually mean the value pipeline is broken, not that performance is extraordinary. Common causes include currency mismatches, cents passed as dollars, fixed values on dynamic revenue, or missing value pass-through. If ignored, budget and bidding decisions are made from fake profitability.',
    howToFix: 'Audit the flagged conversion actions from report row back to Google Ads settings and the GTM value parameter. Confirm value units, currency, and whether the value is dynamic or fixed. Compare a sample order total in your backend with the value recorded in Google Ads for the same time window.',
    example: 'Suspicious: 26 purchases, conversion value / cost = 87.4x\nLikely issue: value is passed in cents or duplicated',
    relatedChecks: ['zero-value-purchases', 'value-mismatch', 'roas-feasibility'],
  },
  {
    id: 'ghost-conversions',
    name: 'Ghost Conversions',
    source: 'report',
    severity: 'critical',
    summary: 'Enabled Google Ads conversion actions have no matching volume in the performance report.',
    why: 'A conversion can be enabled and still be effectively dead. Broken tags, wrong triggers, renamed actions, or label mismatches leave Google Ads bidding toward actions that produce no signal. This is especially dangerous when the action is Primary because campaigns may enter learning with missing feedback.',
    howToFix: 'For each ghost action, check whether the Google Ads conversion label exists in GTM or the site tag and whether the trigger still fires. Use Tag Assistant, GTM Preview, and a real test conversion to verify the hit reaches Google Ads. Disable stale actions or mark them Secondary if they are intentionally retained for history.',
    example: 'Settings: Purchase - Primary - Enabled\nReport: Purchase has 0 conversions across the selected period',
    relatedChecks: ['conversion-label-matching', 'ads-conversion-missing-gtm-tag'],
  },
  {
    id: 'micro-conversion-pollution',
    name: 'Signal Pollution',
    source: 'report',
    severity: 'warning',
    summary: 'Micro-conversion volume is more than 100x macro-conversion volume.',
    why: 'When page views, signups, or other lightweight events dominate the conversion set, Smart Bidding can learn to chase easy actions instead of revenue or qualified leads. The account may show rising conversion volume while pipeline or sales do not improve. Analysts also lose a clear read on whether campaigns are moving real business outcomes.',
    howToFix: 'Mark micro-conversions as Secondary unless they are intentionally used for bidding. Keep the primary goal set focused on purchases, qualified leads, or another downstream action. If you need micro events for learning, isolate them in separate experiments or campaigns instead of mixing them with macro goals.',
    example: 'Macro purchases: 42\nMicro signups/page events: 7,800\nMicro/macro ratio: 185x',
    relatedChecks: ['missing-primary-conversion', 'smart-bidding-volume'],
  },
  {
    id: 'model-attribution-drift',
    name: 'Attribution Drift',
    source: 'report',
    severity: 'info',
    summary: 'Model-attributed conversions differ sharply from standard conversion counts.',
    why: 'Large drift means the selected attribution model is redistributing credit enough to change optimization and reporting conclusions. That can be valid, but it needs to be intentional and understood by the team. Otherwise finance, media buyers, and analytics will argue from different numbers for the same conversion action.',
    howToFix: 'Compare the conversion action attribution model, reporting columns, and business sales cycle. If drift is expected, document which column is used for budget decisions and why. If it is not expected, standardize attribution models across similar actions and inspect whether view-through or cross-device conversions are driving the gap.',
    example: 'Standard conversions: 120\nCurrent model attributed conversions: 43\nDrift: 64%',
    relatedChecks: ['vtc-click-ratio', 'short-attribution-windows'],
  },
  {
    id: 'volume-weighted-duplicates',
    name: 'Active Duplicate Conversions',
    source: 'report',
    severity: 'critical',
    summary: 'Similar conversion names both have active volume, which suggests live double-counting.',
    why: 'Settings duplicates are risky, but active duplicates prove the problem is affecting reports now. Similar actions with volume can represent the same event firing under two names, a renamed conversion that still receives traffic, or an import plus tag pair counting together. This inflates totals and trains bidding on duplicated outcomes.',
    howToFix: 'Compare the flagged pairs by name, source, category, and recent timestamps. Keep one canonical conversion action, merge reporting expectations around it, and mark the duplicate Secondary or remove its tag/import. After changing it, watch both conversion count and conversion value for the next reporting period.',
    example: 'Purchase - Website: 312 conversions\nPurchase Website: 298 conversions\nLikely same event counted twice',
    relatedChecks: ['duplicate-conversions', 'conversion-label-matching'],
  },
  {
    id: 'ads-conversion-missing-gtm-tag',
    name: 'Ads Conversion Missing GTM Tag',
    source: 'cross',
    severity: 'critical',
    summary: 'An enabled Google Ads conversion action has no corresponding conversion tag in GTM.',
    why: 'Google Ads can list an action as enabled even when the site never sends it. If the matching GTM tag is absent, renamed, or never deployed, conversion volume will be zero or incomplete. Primary actions in this state give Smart Bidding no usable feedback.',
    howToFix: 'Match every enabled Google Ads conversion action to a GTM Google Ads conversion tag or a deliberate non-GTM source such as an offline import. For GTM-managed actions, verify conversion ID, label, trigger, and publication status. Disable or mark Secondary any actions that are no longer supposed to receive traffic.',
    example: 'Google Ads: Lead Submit enabled\nGTM: no AW conversion tag or tag name containing Lead Submit',
    relatedChecks: ['ghost-conversions', 'conversion-label-matching'],
  },
  {
    id: 'mismatched-values',
    name: 'Value Mismatch',
    source: 'cross',
    severity: 'critical',
    summary: 'GTM conversion values do not match the values configured or expected in Google Ads.',
    why: 'Value mismatches make revenue reports unreliable even when conversion counts look correct. A fixed GTM value can override dynamic purchase revenue, or Google Ads settings can imply a different value strategy than the tag actually sends. This corrupts ROAS, value-based bidding, and finance reconciliation.',
    howToFix: 'Trace the value from the site dataLayer into the GTM tag and then into Google Ads. If the business uses dynamic revenue, the GTM value parameter should reference a transaction value variable and Google Ads should accept transaction-specific values. If fixed values are intentional, document the model and make sure every platform uses the same assumptions.',
    example: 'GTM value parameter: 1\nGoogle Ads purchase value: 129.99\nExpected: {{DLV - ecommerce.value}}',
    relatedChecks: ['zero-value-purchases', 'roas-sanity'],
  },
  {
    id: 'conversion-label-matching',
    name: 'Conversion ID and Label Matching',
    source: 'cross',
    severity: 'critical',
    summary: 'GTM conversion IDs or labels may not match the intended Google Ads conversion actions.',
    why: 'The conversion ID and label determine which Google Ads action receives the hit. If either value is wrong, the tag can fire successfully while credit lands in the wrong action or nowhere useful. This creates ghost conversions, orphaned actions, and bidding signals attached to the wrong goal.',
    howToFix: 'Open the Google Ads conversion action and copy the AW conversion ID and conversion label directly into the GTM tag. Avoid variable labels unless you have a controlled lookup table and tests for every output. Preview a test conversion and confirm the fired request contains the expected send_to value.',
    example: 'Expected send_to: AW-123456789/AbCdEfGhIjk\nGTM tag sends: AW-123456789/{{Conversion Label}}',
    relatedChecks: ['ghost-conversions', 'ads-conversion-missing-gtm-tag'],
  },
  {
    id: 'meta-missing-pageview',
    name: 'Missing Meta PageView Event',
    source: 'meta',
    severity: 'critical',
    summary: 'The Meta Pixel export does not show an active PageView event.',
    why: 'PageView is the base signal for Meta website audiences, diagnostics, and much of the event funnel context. Without it, remarketing audiences are incomplete and downstream events are harder to validate against site traffic. Campaign optimization can also suffer because Meta sees isolated conversions without the normal browsing path.',
    howToFix: 'Install the Meta base pixel on every page, either directly, through GTM, or through your platform integration. Confirm fbq("track", "PageView") fires once per page load and is not blocked by consent rules after consent is granted. Use Meta Events Manager Test Events to verify active traffic.',
    example: "fbq('init', '1234567890');\nfbq('track', 'PageView');",
    relatedChecks: ['meta-missing-conversion-events', 'meta-ecommerce-funnel'],
  },
  {
    id: 'meta-missing-conversion-events',
    name: 'Missing Meta Conversion Events',
    source: 'meta',
    severity: 'critical',
    summary: 'No active standard Meta conversion event such as Purchase or Lead is present.',
    why: 'Meta campaigns need standard conversion events to optimize for business outcomes. If only PageView or custom diagnostic events exist, campaigns may optimize for traffic instead of purchases or leads. Advertisers lose audience quality, conversion reporting, and stable event matching for downstream actions.',
    howToFix: 'Configure the appropriate standard event for the business model: Purchase for e-commerce, Lead or CompleteRegistration for lead generation, and Subscribe or SubmitApplication where relevant. Fire the event on the final confirmation step, not on button click unless the action is guaranteed. Validate the event in Events Manager and confirm it has recent volume.',
    example: "fbq('track', 'Purchase', { value: 129.99, currency: 'USD' });",
    relatedChecks: ['meta-purchase-missing-value', 'meta-ecommerce-funnel'],
  },
  {
    id: 'meta-purchase-missing-value',
    name: 'Meta Purchase Missing Value',
    source: 'meta',
    severity: 'critical',
    summary: 'Meta Purchase events are firing without usable value data.',
    why: 'Purchase count alone is not enough for value optimization or reliable ROAS reporting. Without value and currency, Meta cannot distinguish order sizes or optimize toward higher-value customers. The result is volume-biased optimization and a weak comparison against Google Ads or backend revenue.',
    howToFix: 'Pass dynamic value and currency parameters with every Meta Purchase event. Pull the value from the order confirmation data, not from a hardcoded tag setting. Check Events Manager diagnostics for missing parameters and compare a few recent orders to reported purchase values.',
    example: "fbq('track', 'Purchase', { value: order.total, currency: 'USD', content_ids: order.skus });",
    relatedChecks: ['meta-missing-conversion-events', 'meta-ecommerce-funnel'],
  },
  {
    id: 'meta-ecommerce-funnel',
    name: 'Meta E-commerce Funnel Events',
    source: 'meta',
    severity: 'warning',
    summary: 'Expected Meta e-commerce funnel events are missing or inactive.',
    why: 'ViewContent, AddToCart, InitiateCheckout, and Purchase give Meta a complete picture of shopping intent. Missing mid-funnel events reduce audience building, funnel diagnostics, and optimization context. Teams then cannot tell whether a campaign fails at product view, cart, checkout, or purchase.',
    howToFix: 'Implement the standard Meta funnel events on their matching site actions and keep event names exactly aligned with Meta standards. Include content IDs and value where available, especially on AddToCart and Purchase. Test the funnel in Events Manager from product page through order confirmation.',
    example: 'Expected events: PageView -> ViewContent -> AddToCart -> InitiateCheckout -> Purchase',
    relatedChecks: ['meta-missing-pageview', 'meta-purchase-missing-value'],
  },
  {
    id: 'tiktok-base-events-active',
    name: 'TikTok Base Events Active',
    source: 'tiktok',
    severity: 'critical',
    summary: 'The TikTok Pixel export has no active events with recorded volume.',
    why: 'No active event volume usually means the base pixel is missing, blocked, disabled, or not receiving traffic. TikTok cannot build audiences, optimize campaigns, or diagnose conversion delivery without a working event stream. Any performance data from this setup is incomplete at best.',
    howToFix: 'Verify the TikTok Pixel base code or GTM template is installed on every page that should be tracked. Check consent behavior, trigger rules, and browser blockers, then use TikTok Events Manager diagnostics or Pixel Helper to confirm live events. Do not launch conversion-optimized campaigns until events are active.',
    example: 'Expected: Page browsing generates ViewContent or ClickButton volume in Events Manager within the test window',
    relatedChecks: ['tiktok-ecommerce-funnel', 'tiktok-completepayment-missing-value'],
  },
  {
    id: 'tiktok-completepayment-missing-value',
    name: 'TikTok CompletePayment Missing Value',
    source: 'tiktok',
    severity: 'critical',
    summary: 'TikTok CompletePayment events are firing without value data.',
    why: "CompletePayment is TikTok's key e-commerce revenue event. If it fires without value and currency, TikTok can count orders but cannot optimize toward order value or report ROAS accurately. This makes high-value and low-value purchases look equivalent to the bidding system.",
    howToFix: 'Pass dynamic value and currency properties with every CompletePayment event. Source the value from the confirmed order total and make sure discounts, taxes, and shipping are handled consistently with your reporting standard. Validate the payload in TikTok Events Manager after a test purchase.',
    example: "ttq.track('CompletePayment', { value: 129.99, currency: 'USD', contents: [{ content_id: 'SKU-1', quantity: 1 }] });",
    relatedChecks: ['tiktok-base-events-active', 'tiktok-ecommerce-funnel'],
  },
  {
    id: 'tiktok-ecommerce-funnel',
    name: 'TikTok E-commerce Funnel Events',
    source: 'tiktok',
    severity: 'warning',
    summary: 'TikTok standard e-commerce funnel events are missing or incomplete.',
    why: 'TikTok needs ViewContent, AddToCart, InitiateCheckout, and CompletePayment to understand where users drop out. Missing funnel events weaken retargeting pools and make optimization depend on a single end event. That is especially fragile for lower-volume stores or campaigns still learning.',
    howToFix: 'Install TikTok standard events at each real funnel step and keep the event names exactly as TikTok expects. Include product IDs, quantities, value, and currency where available. Test product view, cart, checkout, and purchase in Events Manager before trusting campaign optimization.',
    example: 'Expected events: ViewContent -> AddToCart -> InitiateCheckout -> CompletePayment',
    relatedChecks: ['tiktok-base-events-active', 'tiktok-completepayment-missing-value'],
  },
  {
    id: 'linkedin-other-category-overuse',
    name: 'LinkedIn Other Category Overuse',
    source: 'linkedin',
    severity: 'warning',
    summary: 'Too many LinkedIn conversion actions are categorized as Other.',
    why: 'Other is valid in LinkedIn, but it is often used as a catch-all when the action is really Lead, SignUp, Download, KeyPageView, or Purchase. That makes conversion reporting harder to read and weakens the account structure for optimization reviews. Engineers lose the ability to tell which actions represent real funnel stages from the export alone.',
    howToFix: 'Open each Other conversion action in LinkedIn Campaign Manager and map it to the closest standard category. Use Lead for form submits or qualified inquiries, SignUp for account creation, Download for gated assets, KeyPageView for intentionally valuable pages, and Purchase for revenue events. Keep Other only for actions that truly do not fit the standard set.',
    example: 'Problem: Demo Request categorized as Other\nBetter: Demo Request categorized as Lead',
    relatedChecks: ['linkedin-missing-key-conversions', 'linkedin-disabled-key-conversions'],
  },
  {
    id: 'linkedin-unattached-conversions',
    name: 'LinkedIn Unattached Conversions',
    source: 'linkedin',
    severity: 'warning',
    summary: 'Active LinkedIn conversion actions are not attached to any campaign.',
    why: 'A LinkedIn conversion can be active and still be dormant for campaign measurement if no campaigns use it. The tag may fire, the export may show the action, but campaign reporting and optimization will not benefit from it. This is a LinkedIn-specific failure mode because campaign attachment is part of making a conversion action operational.',
    howToFix: 'For each active unattached conversion, decide whether it should be used for reporting or retired. Attach the active business outcomes to the relevant campaigns in Campaign Manager, especially Lead, SignUp, Purchase, and high-intent KeyPageView actions. Disable stale conversions that are kept only as historical artifacts.',
    example: 'Active conversion: Book Demo\nCampaign attachments: 0\nFix: attach Book Demo to the demand-gen campaigns that should optimize for it',
    relatedChecks: ['linkedin-no-active-conversions', 'linkedin-zero-volume-conversions'],
  },
  {
    id: 'linkedin-conversion-window-too-short',
    name: 'LinkedIn Conversion Window Too Short',
    source: 'linkedin',
    severity: 'warning',
    summary: 'LinkedIn conversion windows are shorter than 7 days.',
    why: 'LinkedIn traffic is often B2B or considered purchase traffic. A 3-day or 5-day window can cut off legitimate leads that convert after research, stakeholder review, or a follow-up visit. The tag can be technically correct while campaign reporting undercounts the channels that started the deal.',
    howToFix: 'Compare each conversion action window to the real delay between click and conversion. For B2B lead generation or SaaS, use a wider window such as 30 days post-click unless the business truly converts immediately. Keep short windows only for immediate actions where delayed attribution would be misleading.',
    example: 'Problem: Demo Request uses a 3-day post-click window\nBetter: 30 days post-click for a medium B2B sales cycle',
    relatedChecks: ['linkedin-missing-key-conversions', 'linkedin-unattached-conversions'],
  },
  {
    id: 'conversion-linker-sequencing',
    name: 'Conversion Linker Sequencing',
    source: 'gtm',
    severity: 'critical',
    summary: 'Google Ads conversion tags are not explicitly sequenced to wait for the Conversion Linker tag.',
    why: 'Google documents the Conversion Linker as the tag that stores ad click information in first-party cookies so later conversion tags can connect the session back to the ad click. If the conversion tag can fire before the linker, a valid conversion may be sent before the click identifiers are available. The failure is intermittent, which makes it worse: testing may pass on some page loads while real users lose attribution on slower pages, consent transitions, or redirect-heavy checkout flows. Smart Bidding then receives incomplete conversion and value feedback even though the conversion tag itself appears to fire.',
    howToFix: 'In Google Tag Manager, open Workspace -> Tags and confirm the Google Ads Conversion Linker fires on All Pages or on the earliest page event used by the conversion flow. Open each Google Ads Conversion Tracking tag, go to Advanced Settings -> Tag Sequencing, and set the Conversion Linker as the setup tag that fires before the conversion tag. Preview the container in Tag Assistant, complete a test conversion, and confirm the linker fires before every AW conversion request. Publish only after the sequencing is visible on the same event path that produces the conversion.',
    example: 'Setup tag: Google Ads Conversion Linker\nConversion tag: Google Ads - Purchase\nTag sequencing: Fire setup tag before Google Ads - Purchase fires',
    relatedChecks: ['missing-conversion-linker', 'conversion-label-matching', 'ads-conversion-missing-gtm-tag'],
  },
  {
    id: 'attribution-window-mismatch',
    name: 'Attribution Window vs Sales Cycle Mismatch',
    source: 'ads',
    severity: 'warning',
    summary: 'Enabled conversion actions use click-through windows that do not match the selected sales cycle context.',
    why: 'Google Ads uses the conversion window to decide how long after an ad interaction a conversion can still be attributed to that interaction. A short window on a long-consideration purchase drops legitimate conversions before they can be reported, which makes upper-funnel and remarketing campaigns look weaker than they are. A long window on an immediate purchase can pull in delayed activity that is less likely to be caused by the click. Either mismatch changes the conversion data used by automated bidding and makes period-over-period reporting harder to defend.',
    howToFix: 'In Google Ads, open Tools & Settings -> Measurement -> Conversions, then select each flagged conversion action. Edit the click-through conversion window to match the real buying cycle: short direct-response actions often fit 7 to 14 days, medium cycles often need 30 days, and long B2B or considered purchases may need 60 to 90 days. Keep related conversion actions on comparable windows so campaign and goal reporting do not mix incompatible assumptions. After the change, annotate the date and review conversion lag before judging performance.',
    example: 'Problem: Demo Request uses a 7-day click window with a long sales cycle\nBetter: Demo Request click-through conversion window = 60 days',
    relatedChecks: ['short-attribution-windows', 'model-attribution-drift', 'smart-bidding-volume'],
  },
  {
    id: 'cross-domain-tracking',
    name: 'Cross-Domain Tracking Misconfigured',
    source: 'gtm',
    severity: 'warning',
    summary: 'The container references multiple domains, but the Conversion Linker is not configured with auto-link domains.',
    why: 'Google Tag Manager cross-domain measurement depends on linker configuration so identifiers can move across related domains without starting a new unconnected session. This matters when the user moves from the marketing site to a checkout, booking engine, donation platform, or lead form hosted on another domain. If the linker is missing those domains, Google Ads may see the conversion page without the click context that started the visit. The result is under-attribution, split sessions, and weaker remarketing or bidding signals for funnels that leave the main site.',
    howToFix: 'In Google Tag Manager, open Workspace -> Tags -> Google Ads Conversion Linker. Under Cross domain tracking, add every domain that participates in the conversion path to the auto-link domains field, including payment, booking, and subdomain hosts. Keep the tag firing on All Pages, then use Preview mode to click from the source domain to the destination domain and confirm the linker parameter is appended and consumed. Publish after testing the real navigation path, not only a direct page load on the destination domain.',
    example: 'Auto-link domains: example.com, checkout.example-payments.com, booking.example.net\nTrigger: All Pages',
    relatedChecks: ['missing-conversion-linker', 'conversion-linker-sequencing', 'conversion-label-matching'],
  },
  {
    id: 'currency-consistency',
    name: 'Inconsistent Currency Codes',
    source: 'ads',
    severity: 'critical',
    summary: 'Google Ads conversion actions are reporting values in more than one currency code.',
    why: 'Google conversion tags and imports support currency values, but value-based reporting assumes the account team knows what unit each value represents. Mixing USD, CAD, EUR, or blank currencies inside the same conversion set can make ROAS and conversion value totals impossible to reconcile against the store or CRM. It can also make automated bidding compare revenue signals that are not economically equivalent. This is a critical measurement issue because the conversion count may look fine while the value column is no longer a dependable business metric.',
    howToFix: 'In Google Ads, open Tools & Settings -> Measurement -> Conversions and inspect the value settings for each flagged action. For GTM-managed website conversions, open GTM -> Workspace -> Tags -> the Google Ads Conversion Tracking tag and set Currency Code to the same ISO code used by the site revenue system, usually through a Data Layer Variable such as ecommerce.currency. For imports, standardize the Conversion Currency column before upload. Re-test one purchase or import row per currency path and confirm Google Ads reports the expected currency code.',
    example: 'Expected currency code: USD\nGTM Currency Code field: {{DLV - ecommerce.currency}}\ndataLayer value: ecommerce.currency = "USD"',
    relatedChecks: ['zero-value-purchases', 'mismatched-values', 'roas-sanity'],
  },
  {
    id: 'debug-tags-in-production',
    name: 'Preview/Debug Tags in Production',
    source: 'gtm',
    severity: 'warning',
    summary: 'Tags with debug, test, preview, staging, or dev names are firing on All Pages in the production container.',
    why: 'Debug tags are useful during implementation, but they should not remain active on the production all-pages path. They can send test conversions, duplicate diagnostic events, leak implementation details to third-party endpoints, or create noise that makes Tag Assistant and platform diagnostics harder to read. If a debug tag uses a Google Ads, GA4, or custom HTML template, it may also affect consent behavior or performance on every page load. The risk is not the name alone, but the combination of a test-oriented tag and a broad production trigger.',
    howToFix: 'In Google Tag Manager, open Workspace -> Tags and filter for names containing debug, test, preview, staging, or dev. For each flagged tag, remove the All Pages trigger, pause the tag, or move the logic into a dedicated testing workspace or environment. If the tag is still needed, restrict it with a Preview Mode, hostname, or environment condition that cannot match production users. Submit the container only after Preview mode shows no debug-named tag firing on the public production hostname.',
    example: 'Problem: Debug - GA4 event fires on All Pages\nBetter: Debug - GA4 event fires only when Page Hostname equals staging.example.com',
    relatedChecks: ['consent-violations', 'duplicate-conversions', 'missing-conversion-linker'],
  },
  {
    id: 'duplicate-datalayer-paths',
    name: 'Duplicate Data Layer Variable Paths',
    source: 'gtm',
    severity: 'warning',
    summary: 'Multiple GTM Data Layer Variables read from the same dataLayer path.',
    why: 'Google recommends using a consistent data layer structure so tags can reliably read the values they need. When several variables read the same path, teams often update one variable name, default value, or version setting while another copy continues to feed production tags. That creates subtle mismatches where two tags appear to use the same business value but resolve it differently at runtime. The audit flags this because duplicated paths increase maintenance risk around revenue, currency, transaction ID, user data, and trigger conditions.',
    howToFix: 'In Google Tag Manager, open Workspace -> Variables -> User-Defined Variables and group Data Layer Variables by their Data Layer Variable Name. Pick one canonical variable for each path, update tags and triggers to reference it, and archive the duplicates after Preview mode confirms the canonical variable resolves on the correct event. Use clear names such as DLV - ecommerce.value and avoid creating per-tag copies unless they intentionally use different defaults or data layer versions. Re-export the container and verify each important path appears once.',
    example: 'Problem:\nDLV - value -> ecommerce.value\nDLV - purchase revenue -> ecommerce.value\n\nBetter:\nDLV - ecommerce.value -> ecommerce.value',
    relatedChecks: ['missing-datalayer-variables', 'ecommerce-datalayer-structure', 'datalayer-version-conflicts'],
  },
  {
    id: 'data-driven-eligibility',
    name: 'Data-Driven Attribution Volume Check',
    source: 'ads',
    severity: 'info',
    summary: 'One or more enabled conversion actions use data-driven attribution and need volume review in Google Ads.',
    why: 'Google Ads data-driven attribution assigns credit based on observed paths rather than a fixed rule, and Google positions it as a model that uses account performance data when enough signal is available. If a low-volume action is set to data-driven attribution, the model may be noisy or unavailable for the decision the team is trying to make. The practical risk is interpretation: bidding and reporting can be discussed as if the model is precise when the underlying conversion action has too little recent activity. This check is informational because eligibility and modeling status must be confirmed in the Google Ads UI.',
    howToFix: 'In Google Ads, open Tools & Settings -> Measurement -> Attribution, then review conversion actions on the Switch to DDA or attribution model screens. For each flagged action, confirm Google Ads marks it eligible and that recent conversion volume is sufficient for the business decision being made. If volume is weak, consolidate duplicate actions, keep the macro action Primary, or use a simpler attribution model until the action has steadier data. Document the selected model so reporting, bidding, and client-facing decks use the same attribution assumption.',
    example: 'Review target: Purchase\nAttribution model: Data-driven\nRecent volume: confirm eligibility and stability in Google Ads Attribution before relying on the model',
    relatedChecks: ['model-attribution-drift', 'attribution-window-mismatch', 'smart-bidding-volume'],
  },
  {
    id: 'conversion-naming-alignment',
    name: 'GTM-Ads Conversion Naming Alignment',
    source: 'ads',
    severity: 'info',
    summary: 'Google Ads conversion tag names in GTM do not clearly match enabled conversion action names in Google Ads.',
    why: 'Google Ads matching is controlled by conversion ID and label, not by the friendly name, so a naming mismatch does not automatically break tracking. It does make the setup harder to audit because the person reviewing GTM cannot confidently tell which Google Ads action receives each tag hit. That increases the chance of editing the wrong tag, leaving renamed actions active, or missing duplicates during a cleanup. Clear naming is especially important when agencies hand off accounts or when multiple conversion actions share the same category.',
    howToFix: 'In Google Ads, open Tools & Settings -> Measurement -> Conversions and copy the exact active conversion action names that should be tracked from GTM. In Google Tag Manager, open Workspace -> Tags and rename each Google Ads Conversion Tracking tag so the business action, source, and Ads action name are recognizable. Do not change conversion IDs or labels during the naming cleanup unless you are intentionally remapping the tag. Preview one conversion and compare the GTM tag name, send_to value, and Google Ads action name before publishing.',
    example: 'Google Ads action: Purchase - Website\nGTM tag name: Google Ads - Purchase - Website\nsend_to: AW-123456789/AbCdEfGhIjk',
    relatedChecks: ['conversion-label-matching', 'ads-conversion-missing-gtm-tag', 'volume-weighted-duplicates'],
  },
  {
    id: 'datalayer-version-conflicts',
    name: 'Mixed Data Layer Versions',
    source: 'gtm',
    severity: 'warning',
    summary: 'The GTM container mixes version 1 and version 2 Data Layer Variables.',
    why: 'Data Layer Variable version changes how GTM resolves nested objects and keys, so mixed versions can make two variables behave differently against the same dataLayer payload. Version 2 is normally the expected choice for modern ecommerce objects because it can read nested paths such as ecommerce.value and ecommerce.items. If one purchase tag reads a v2 variable while another uses v1, the account can end up with missing values, wrong defaults, or inconsistent trigger decisions. This undermines the predictability Google emphasizes for data layer implementations.',
    howToFix: 'In Google Tag Manager, open Workspace -> Variables and inspect every Data Layer Variable. Standardize modern ecommerce and conversion variables on Data Layer Version 2 unless a specific legacy variable requires version 1 behavior. After changing a variable, use Preview mode on the exact event that fires the conversion tag and confirm value, currency, transaction_id, and item paths still resolve. Publish only after all affected tags show the same resolved values as before or the intended corrected values.',
    example: 'Variable: DLV - ecommerce.value\nData Layer Variable Name: ecommerce.value\nData Layer Version: Version 2',
    relatedChecks: ['duplicate-datalayer-paths', 'missing-datalayer-variables', 'ecommerce-datalayer-structure'],
  },
  {
    id: 'conversion-funnel-coverage',
    name: 'Conversion Tracking Funnel Coverage',
    source: 'cross',
    severity: 'warning',
    summary: 'Enabled Google Ads conversions do not cover enough major funnel stages across awareness, consideration, conversion, and retention.',
    why: 'Google Ads conversion measurement is meant to track valuable actions such as purchases, sign-ups, and other customer activity after ad interactions. When only one end-stage action is tracked, teams lose visibility into whether media is generating qualified visits, product interest, checkout progress, leads, purchases, or repeat value. That can make optimization brittle for lower-volume accounts because Smart Bidding and analysts see only sparse macro outcomes. The goal is not to count every click as a conversion, but to maintain a defensible funnel map with Primary macro actions and Secondary diagnostic actions.',
    howToFix: 'In Google Ads, open Tools & Settings -> Measurement -> Conversions and list the enabled actions by funnel stage. Add or repair missing diagnostic actions for important stages, then set only the true business outcome as Primary and keep supporting micro-conversions Secondary unless they are intentionally used for bidding. In GTM, open Workspace -> Tags and verify each website-based action has a matching trigger on the real page or event, not only a button click that can fail validation. Re-run the full audit with both GTM and Google Ads exports to confirm no more than one major stage is missing.',
    example: 'Primary: Purchase or Qualified Lead\nSecondary: Landing Page Visit, Product View, Add to Cart, Begin Checkout, Repeat Purchase',
    relatedChecks: ['micro-conversion-pollution', 'missing-primary-conversion', 'conversion-naming-alignment'],
  },
  {
    id: 'pinterest-conversion-api-parity',
    name: 'Pinterest Conversion API Parity',
    source: 'pinterest',
    severity: 'warning',
    summary: 'Pinterest browser events have no matching server-side Conversion API volume.',
    why: 'Pinterest positions the Conversion API as a way to send conversion events from the server alongside the browser tag. If browser events exist but the server stream is missing, measurement depends on client-side requests that can be blocked by browsers, consent timing, or network conditions. The result is weaker event durability and less defensible attribution when the browser and server sources should be backing each other up.',
    howToFix: 'Map each important Pinterest Tag event to the equivalent Conversion API event and send the same business action from the server where possible. Include event time, event name, value, currency, and matching identifiers needed for deduplication and enhanced match. Confirm Events Manager shows browser and server volume for the same major events before relying on campaign reporting.',
    example: 'Browser event: Checkout\nServer event: Checkout\nShared fields: event_id, value, currency, order_id, customer match fields',
    relatedChecks: ['pinterest-tag-configuration-quality', 'pinterest-checkout-missing-value'],
  },
  {
    id: 'pinterest-tag-configuration-quality',
    name: 'Pinterest Tag Configuration Quality',
    source: 'pinterest',
    severity: 'warning',
    summary: 'Pinterest tag naming, enhanced match, or currency setup is inconsistent.',
    why: 'Pinterest setup quality problems often do not stop events from firing, but they make the event stream harder to defend. Reusing a partner name as a tag name obscures ownership, missing enhanced match weakens matching quality, and mixing EUR and USD values makes revenue reporting hard to reconcile. These are measurement governance issues: the data exists, but the account team cannot trust what it means without cleanup.',
    howToFix: 'Use clear, distinct names for the Pinterest Tag and any partner or integration layer. Enable enhanced match where it is appropriate for the consent and data policy in scope. Standardize value events on one expected currency, then re-test Checkout and Lead events in Pinterest Events Manager.',
    example: 'Problem: partnerName = Main Tag, tagName = Main Tag, currencies = USD and EUR\nBetter: partnerName = Shopify, tagName = US Store Pinterest Tag, currency = USD',
    relatedChecks: ['pinterest-conversion-api-parity', 'pinterest-checkout-missing-value'],
  },
  {
    id: 'twitter-event-id-format',
    name: 'Twitter/X Event ID Format',
    source: 'twitter',
    severity: 'critical',
    summary: 'Twitter/X website events do not use the expected tw-XXXX-XXXX event ID format.',
    why: 'The event ID is the routing key that tells the Twitter/X website tag which configured event should receive the hit. If the ID is malformed, the tag can fire in the browser while the conversion never lands in the intended event. That creates a hard-to-spot failure where network activity exists but optimization and reporting are pointed at missing or incorrect conversion signals.',
    howToFix: 'Copy the event ID directly from Twitter/X Ads Events Manager into the website tag or GTM template. Avoid hand-typing IDs or transforming them through variables unless there is a tested lookup table. Fire a test conversion and confirm the request contains the same tw-prefixed ID shown in the platform UI.',
    example: 'Expected: tw-abc123-def456\nProblem: abc123-def456 or TW abc123 def456',
    relatedChecks: ['twitter-conversion-id-required', 'twitter-deduplication-conversion-id'],
  },
  {
    id: 'twitter-deduplication-conversion-id',
    name: 'Twitter/X conversion_id Deduplication',
    source: 'twitter',
    severity: 'warning',
    summary: 'Twitter/X conversion events are missing or reusing conversion_id values.',
    why: 'Twitter/X uses conversion identifiers to recognize the same business event when it arrives from more than one path, such as browser and server. Without a stable conversion_id, repeated hits can inflate conversion counts, while missing IDs make server-side alignment harder to audit. Reused IDs across different orders or leads create the opposite risk by collapsing distinct events.',
    howToFix: 'Generate a unique conversion_id from the order ID, lead ID, or another stable transaction identifier. Pass the same ID only when browser and server payloads represent the same event. Review recent events for missing IDs and for repeated IDs that span different users or conversion actions.',
    example: 'Purchase order 10492\nBrowser conversion_id: 10492\nServer conversion_id: 10492',
    relatedChecks: ['twitter-conversion-id-required', 'twitter-event-id-format'],
  },
  {
    id: 'snapchat-pixel-id-format',
    name: 'Snap Pixel ID Format',
    source: 'snapchat',
    severity: 'critical',
    summary: 'The Snap Pixel ID is missing or does not match the expected UUID-style format.',
    why: 'Snap Pixel events need to be associated with the correct pixel before they can populate audiences, diagnostics, and conversion reporting. A copied-short, malformed, or stale ID can send events into the wrong asset or prevent them from being recognized. The event code may still execute, so the practical risk is silent measurement loss rather than an obvious page error.',
    howToFix: 'Copy the Pixel ID from Snapchat Events Manager and compare it against every GTM tag, direct site tag, and commerce integration. Keep one canonical ID per property unless there is an intentional multi-pixel setup. Test PAGE_VIEW and PURCHASE after the change and confirm they appear under the expected Snap Pixel.',
    example: 'Expected shape: 123e4567-e89b-12d3-a456-426614174000',
    relatedChecks: ['snapchat-missing-page-view', 'snapchat-capi-dedup-currency'],
  },
  {
    id: 'snapchat-capi-dedup-currency',
    name: 'Snap CAPI, Deduplication, and Currency Alignment',
    source: 'snapchat',
    severity: 'warning',
    summary: 'Snap Pixel and Conversions API events are not aligned on deduplication or currency.',
    why: 'Snap recommends aligning browser pixel and Conversions API implementations so the same user action can be matched without double-counting. Missing deduplication IDs make browser plus server setups vulnerable to inflated counts, while missing CAPI volume leaves the account dependent on browser-only measurement. Mixed currencies add another reporting risk because conversion value totals no longer describe one economic unit.',
    howToFix: 'Send the same deduplication ID on matching Snap Pixel and Conversions API events, normally derived from the order ID, lead ID, or event ID. Confirm server-side volume appears for key events such as PURCHASE and SIGN_UP. Standardize currency on the value events and validate a real transaction against the value and currency shown in Events Manager.',
    example: 'PURCHASE event_id: order-10492\nPixel currency: USD\nCAPI currency: USD',
    relatedChecks: ['snapchat-pixel-id-format', 'snapchat-purchase-missing-value'],
  },
];

export function getExplainer(id: string): CheckExplainer | undefined {
  return explainers.find((explainer) => explainer.id === id);
}

export function getExplainersBySource(source: ExplainerSource): CheckExplainer[] {
  return explainers.filter((explainer) => explainer.source === source);
}
